openapi: 3.0.0
info:
  version: 1.0.0
  title: My API
  description: My Description
paths:
  /api/weather/temperature:
    post:
      summary: Your POST endpoint
      tags: []
      responses:
        '201':
          description: Created
      operationId: app.post_api_weather_temperature
      description: Accepts JSON with temperature details.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/temperature'
  /api/weather/humidity:
    post:
      summary: Your POST endpoint
      tags: []
      responses:
        '201':
          description: Created
      operationId: app.post_api_weather_humidity
      description: Accepts JSON with humidity details.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/humidity'
components:
  schemas:
    temperature:
      title: temperature
      type: object
      properties:
        device_id:
          type: string
          x-stoplight:
            id: owudgm6kikkbp
        temperature:
          type: integer
          x-stoplight:
            id: fj8xwag355vzs
        timestamp:
          type: string
          x-stoplight:
            id: iwvgwcel6neqf
        location:
          type: string
          x-stoplight:
            id: sx26q7qutfbx6
    humidity:
      title: humidity
      type: object
      properties:
        device_id:
          type: string
          x-stoplight:
            id: rfjedefzjyaqm
        humidity:
          type: integer
          x-stoplight:
            id: ht1h4a1ddg637
        timestamp:
          type: string
          x-stoplight:
            id: lf0vi08rwewav
        location:
          type: string
          x-stoplight:
            id: 961vz5sst1j7n