version: 1
datastore:
  filename: stats.json
scheduler:
  interval: 10

eventstores:
  temperature:
    url: http://storage/storage/temperature
  humidity:
    url: http://storage/storage/humidity