- name: Git pull and restart Docker on AWS t3.medium instance
  hosts: web
  become: yes
  vars:
    git_repo_dir: "/home/ubuntu/ACIT3855Combined"
    log_dir: "{{ git_repo_dir }}/logs"
    log_files:
      - analyzer.log
      - processing.log
      - receiver.log
      - storage.log

  tasks:
    - name: Ensure required packages are installed
      apt:
        name: git
        state: present

    - name: Pull latest code from Git
      git:
        repo: "https://github.com/rylanraj/ACIT3855Combined.git"
        dest: "{{ git_repo_dir }}"
        version: main
        update: yes
      become_user: ubuntu

    - name: Stop running containers
      community.docker.docker_compose:
        project_src: "{{ git_repo_dir }}"
        state: absent
        remove_volumes: true

    - name: Remove old logs
      file:
        path: "{{ log_dir }}"
        state: absent

    - name: Recreate logs directory
      file:
        path: "{{ log_dir }}"
        state: directory
        mode: '0755'

    - name: Create log files and set permissions
      file:
        path: "{{ log_dir }}/{{ item }}"
        state: touch
        mode: '0666'
      loop: "{{ log_files }}"

    - name: Start Docker containers
      community.docker.docker_compose:
        project_src: "{{ git_repo_dir }}"
        build: yes
        state: present
        restarted: yes
